In [1]:
import numpy as np

In [15]:
x = np.ones(50,dtype=np.int16)
print(x)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]


20.000000002040817

In [29]:
y = []
i = 1
# while len(y) < 50:
interval= 19/49

while round(i,5) <= 20:
    y.append(round(i,5))
    i += interval
    
y = np.array(y)
print(y)
len(y)

[ 1.       1.38776  1.77551  2.16327  2.55102  2.93878  3.32653  3.71429
  4.10204  4.4898   4.87755  5.26531  5.65306  6.04082  6.42857  6.81633
  7.20408  7.59184  7.97959  8.36735  8.7551   9.14286  9.53061  9.91837
 10.30612 10.69388 11.08163 11.46939 11.85714 12.2449  12.63265 13.02041
 13.40816 13.79592 14.18367 14.57143 14.95918 15.34694 15.73469 16.12245
 16.5102  16.89796 17.28571 17.67347 18.06122 18.44898 18.83673 19.22449
 19.61224 20.     ]


50

In [30]:
z = np.linspace(1,20,50)
print(z)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [36]:
w = np.sum(abs(z - y))
w

0.00012244897958213485

In [35]:
sum(w)

0.00012244897958213485

# For question 2

In [38]:
import numpy as np
import random

In [40]:
M = np.ones(1)
np.array(M)
i = 0
while M[-1] != 7:
    
    rand_val = random.randint(1,10)
    print(rand_val)
    M = np.append( [M],rand_val)
    i+=1
    if i == 30:
        
        break
# print(i)
print(M)
mean_M = sum(M)/len(M)
print('The number of elements in M is {} and their mean value = {}'.format(len(M), mean_M))

9
5
9
3
4
8
9
10
9
7
[ 1.  9.  5.  9.  3.  4.  8.  9. 10.  9.  7.]
The number of elements in M is 11 and their mean value = 6.7272727272727275


# For question 3

In [44]:
a = np.array([  8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])
reshaped_a = a.reshape(5,5)
print(reshaped_a)

[[ 8.  3. 10.  8.  2.]
 [ 2. 10. 10.  5. 10.]
 [ 2. 10.  9. 10.  9.]
 [ 4.  2.  8.  7.  4.]
 [ 1.  4.  5.  6.  6.]]


In [48]:
k = 0
for elements in reshaped_a.flat:
    
    if elements == 5 or elements == 8:
        
        element_index = np.where(reshaped_a == elements)
        locations = list(zip(element_index[0], element_index[1]))
#         for location in locations:
            
        print(elements, locations)
        k += 1
    if elements == 1:
        
        print('you win')
        
print(""""The number of 5's and 8's = {}""".format(k))

8.0 [(0, 0), (0, 3), (3, 2)]
8.0 [(0, 0), (0, 3), (3, 2)]
5.0 [(1, 3), (4, 2)]
8.0 [(0, 0), (0, 3), (3, 2)]
you win
5.0 [(1, 3), (4, 2)]
"The number of 5's and 8's = 5


# For question 4

In [8]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x = np.array([1,3,4]).reshape(3,1)
x

array([[1],
       [3],
       [4]])

In [45]:
B = np.array([(-0.1,-0.2,-0.3),(3,10,2),(4,2,0.5)]).reshape(3,3)
B

array([[-0.1, -0.2, -0.3],
       [ 3. , 10. ,  2. ],
       [ 4. ,  2. ,  0.5]])

In [46]:
A_B = A * B
A_B

array([[-0.1, -0.4, -0.9],
       [12. , 50. , 12. ],
       [28. , 16. ,  4.5]])

In [62]:
A__B = np.dot(A,B)
A__B

array([[17.9, 25.8,  5.2],
       [38.6, 61.2, 11.8],
       [59.3, 96.6, 18.4]])

In [63]:
np.cross(A,B)

array([[ 1.11022302e-16, -5.55111512e-17,  0.00000000e+00],
       [-5.00000000e+01,  1.00000000e+01,  2.50000000e+01],
       [-1.40000000e+01,  3.25000000e+01, -1.80000000e+01]])